go:
  # Whenever the Go version is updated here,
  # .circle/config.yml should also be updated.
  version: 1.23
repository:
  path: github.com/waitingsong/zfs_exporter/v2
build:
  flags: -a -tags netgo
  ldflags: |
    -X github.com/prometheus/common/version.Version={{.Version}}
    -X github.com/prometheus/common/version.Revision={{.Revision}}
    -X github.com/prometheus/common/version.Branch={{.Branch}}
    -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
    -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
crossbuild:
  platforms:
    - linux
    - illumos
    - darwin
    - freebsd
    - netbsd
    - dragonfly
tarball:
  files:
    - LICENSE
    - CHANGELOG.md
