go:
  # Whenever the Go version is updated here,
  # .circle/config.yml should also be updated.
  version: 1.23
repository:
  path: github.com/waitingsong/zfs_exporter/v3
build:
  flags: -a -tags netgo
  ldflags: |
    -X github.com/prometheus/common/version.Version={{.Version}}
    -X github.com/prometheus/common/version.Revision={{.Revision}}
    -X github.com/prometheus/common/version.Branch={{.Branch}}
    -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
    -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
crossbuild:
  platforms:
    - linux/amd64
    - linux/arm64
    - freebsd/amd64
    - freebsd/arm64
    - darwin/amd64
    - darwin/arm64
tarball:
  files:
    - LICENSE
    - CHANGELOG.md
